const ExperienceDB = [
  {
    id: "EX0",
    JobRole: "Data Analyst",
    JobType: "Contract",
    StartDay: "March 2025",
    EndDay: "Present",
    Company: "The Analyst Hub",
    Nature: "Remote",
    url: "https://www.theanalysthub.ng/",
    Description: [
      "Collaborated with cross-functional teams to analyze datasets from education, healthcare, real estate, and manufacturing sectors.",
      "Cleaned, explored, and visualized large datasets to uncover trends and deliver actionable insights.",
      "Developed dashboards and reports that improved internal reporting and supported executive decision-making.",
    ],
  },
  {
    id: "EX122",
    JobRole: "Data Analyst",
    JobType: "Freelance",
    StartDay: "January 2023",
    EndDay: "Present",
    Company: "Upwork/Fiverr",
    Nature: "Remote",
    url: "",
    Description: [
      "Built custom Excel and Power BI dashboards for SMEs, visualizing KPIs on sales, marketing campaigns, and operational efficiency. Also automated recurring reporting processes using Power Query and scheduled refreshes in Power BI.",
      "Delivered SQL-driven insights from relational databases for client projects, supporting performance tracking and revenue optimization.",
      "Collaborated with business owners to translate requirements into data models, visuals, and actionable insights.",
    ],
  },
  {
    id: "EX1",
    JobRole: "Data Analyst",
    JobType: "",
    StartDay: "February 2023",
    EndDay: "March 2025",
    Company: "Accessible Publishers Limited",
    Nature: "Onsite",
    url: "https://www.accessiblepublishers.com/",
    Description: [
      "Designed and deployed interactive Power BI dashboards to monitor press machine output, sales transactions, and employee performance, improving decision-making efficiency by 30%. Conducted weekly and monthly trend analysis on sales, marketing, and operational datasets to identify growth opportunities and bottlenecks. ",
      "Developed and optimized data models using DAX and Power Query, enabling scalable and automated reporting processes. Also implemented data cleansing and quality assurance workflows in Excel and Power Query, improving data reliability by 25%.",
      "Trained staff through Excel and Power BI tutorials, enhancing data literacy and adoption across the organization.",
      "Setting up a database for the company datasets for different departments.",
      "Setting up processes and systems to make working with data more efficient",
      "Researching new ways to make use of data.",
      "Analyzed data to award recognition to supervisors, staffs, casuals, apprentice for their performance for every month.",
      "Developing automated processes for data scraping.",
      "Analyzing data to identify trends",
    ],
  },
  {
    id: "EX2",
    JobRole: "Quantity Surveyor",
    JobType: "",
    StartDay: "February 2022",
    EndDay: "March 2025",
    Company: "Best Technologies Limited",
    Nature: "OnSite",
    url: "https://www.besttechnologiesltd.com/",
    Description: [
      "Measure building and civil engineering works, prepare bills of quantities, and manage material schedules and work programs.",
      "I oversee site engineering and procurement of materials and prepare interim valuations",
      "Price un-priced bills of quantities for tendering and procure materials for the site.",
    ],
  },
  {
    id: "EX3",
    JobRole: "Data Analysis Tutor",
    JobType: "",
    StartDay: "February 2023",
    EndDay: "March 2025",
    Company: "Best Technologies Limited",
    Nature: "Part Time",
    url: "https://www.besttechnologiesltd.com/",
    Description: [
      "Mentor and guide data analysis newbies",
      "Organize data analysis tutorial classes but online and onsite for data analyst newbies",
      "Organize monthly Microsoft Excel training for Students",
      "Train company staff on how to use excel make their work faster and more efficient.",
    ],
  },
  {
    id: "EX4",
    JobRole: "Mentor (Tech4Governance)",
    JobType: "",
    StartDay: "September 2024",
    EndDay: "December 2024",
    Company: "Aspilos Foundation",
    Nature: "Remote",
    url: "https://aspilosfoundation.org.ng/",
    Description: [
      "Guided young tech professionals in developing Civic Tech Solutions to address governance challenges.",
      "Provided mentorship on data-driven decision-making and the integration of technology for social impact.",
      "Conducted workshops on data analysis, visualization, and solution prototyping.",
    ],
  },
  {
    id: "EX5",
    JobRole: "FrontEnd Developer",
    JobType: "Volunteer",
    StartDay: "April 2022",
    EndDay: "December 2023",
    Company: "United State of Africa",
    Nature: "Remote",
    url: "https://usafrikagov.com/",
    Description: [
      "I collaborate with designers and back-end developers to implement and maintain user interfaces for the company websites and web applications.",
      "I collaborate with other frontend developers to work on the company website and web applications.",
      "I actively participate in agile development processes, including sprint planning, daily stand-ups, and retrospectives, to ensure timely delivery of high-quality software.",
      "I write clean, efficient, and maintainable code using React JS, Next JS framework with tailwind CSS for the styling.",
      "Worked on implementation of website Figma design.",
      "I ensure cross-browser compatibility and responsiveness of web interfaces across various devices and screen sizes",
      "I implement user interface designs with a keen eye for detail, ensuring visual consistency and adherence to brand guidelines.",
      "I conduct several test and debugging of code to ensure the functionality and integrity of web interfaces.",
      "I also collaborate with cross-functional teams to understand project requirements and deliver high-quality solutions within specified timelines.",
    ],
  },
];

export default ExperienceDB;
