const ExperienceDB = [
  {
    id: "EX0",
    JobRole: "Data Analyst",
    JobType: "Contract",
    StartDay: "March 2025",
    EndDay: "Present",
    Company: "The Analyst Hub",
    Nature: "Remote",
    url: "https://www.theanalysthub.ng/",
    Description: [
      "I supported ongoing analytics initiatives by working with structured datasets to deliver accurate reporting and actionable insights. My responsibilities focused on data preparation, analysis, and visualization to help stakeholders understand performance trends and data quality issues.",
      "Extracted, cleaned, and transformed datasets using SQL, Python, and Excel to support analytics and reporting needs.",
      "Conducted exploratory data analysis to identify trends, patterns, and performance gaps across marketing and engagement data.",
      "Built and maintained Power BI dashboards to visualize key metrics and track performance over time.",
      "Performed data validation and consistency checks to ensure reliable outputs across reporting workflows.",
      "Translated stakeholder requirements into structured analytical approaches and documented findings for clarity and reuse.",
    ],
  },
  {
    id: "EX122",
    JobRole: "Data Analyst",
    JobType: "Freelance",
    StartDay: "January 2023",
    EndDay: "Present",
    Company: "Upwork/Fiverr",
    Nature: "Remote",
    url: "",
    Description: [
      "I worked with clients across different industries, supporting short-term and ongoing data analysis needs. I independently managed projects from data collection through reporting, ensuring accuracy and clarity in all deliverables.",
      "Extracted and analyzed data from SQL databases, Excel files, Google Sheets, and cloud-based sources.",
      "Designed Excel-based analysis workflows using Power Query, PivotTables, formulas, and validation rules to standardize reporting.",
      "Performed descriptive and trend analysis to identify patterns, inefficiencies, and opportunities for improvement.",
      "Conducted data quality checks, reconciliation, and error reviews to maintain reporting accuracy.",
      "Built dashboards and summary reports that translated complex datasets into clear, decision-ready insights.",
      "Managed multiple projects concurrently while meeting deadlines and maintaining high attention to detail.",
    ],
  },
  {
    id: "EX1",
    JobRole: "Data Analyst",
    JobType: "",
    StartDay: "February 2023",
    EndDay: "March 2025",
    Company: "Accessible Publishers Limited",
    Nature: "Onsite",
    url: "https://www.accessiblepublishers.com/",
    Description: [
      "Analyzed sales, operations, and customer data to support data-driven decision-making across departments.",
      "Built and maintained Excel and Power BI dashboards to monitor KPIs, trends, and operational performance.",
      "Performed routine data cleaning, validation, and reconciliation to improve data reliability and consistency.",
      "Conducted trend analysis and ad-hoc investigations to uncover risks, issues, and improvement opportunities.",
      "Collaborated with internal stakeholders to understand reporting needs and deliver accurate analytical outputs.",
      "Improved reporting accuracy by approximately 25% through structured data quality checks and validation processes.",
      "Analyzed data to award recognition to supervisors, staffs, casuals, apprentice for their performance for every month.",
      "Developing automated processes for data scraping.",
      "Analyzing data to identify trends",
    ],
  },
  {
    id: "EX2",
    JobRole: "Quantity Surveyor",
    JobType: "",
    StartDay: "February 2022",
    EndDay: "March 2025",
    Company: "Best Technologies Limited",
    Nature: "OnSite",
    url: "https://www.besttechnologiesltd.com/",
    Description: [
      "Measure building and civil engineering works, prepare bills of quantities, and manage material schedules and work programs.",
      "I oversee site engineering and procurement of materials and prepare interim valuations",
      "Price un-priced bills of quantities for tendering and procure materials for the site.",
    ],
  },
  {
    id: "EX3",
    JobRole: "Data Analysis Tutor",
    JobType: "",
    StartDay: "February 2023",
    EndDay: "March 2025",
    Company: "Best Technologies Limited",
    Nature: "Part Time",
    url: "https://www.besttechnologiesltd.com/",
    Description: [
      "Delivered hands-on training in SQL, Python, Excel, and Power BI.",
      "Guided learners through data cleaning, exploratory data analysis, reporting, and dashboard creation.",
      "Demonstrated best practices for data validation, accuracy checks, and analytical thinking.",
      "Supported learners with project guidance, interpretation of results, and presentation of insights.",
    ],
  },
  {
    id: "EX4",
    JobRole: "Mentor (Tech4Governance)",
    JobType: "",
    StartDay: "September 2024",
    EndDay: "December 2024",
    Company: "Aspilos Foundation",
    Nature: "Remote",
    url: "https://aspilosfoundation.org.ng/",
    Description: [
      "Guided young tech professionals in developing Civic Tech Solutions to address governance challenges.",
      "Provided mentorship on data-driven decision-making and the integration of technology for social impact.",
      "Conducted workshops on data analysis, visualization, and solution prototyping.",
    ],
  },
  {
    id: "EX5",
    JobRole: "FrontEnd Developer",
    JobType: "Volunteer",
    StartDay: "April 2022",
    EndDay: "December 2023",
    Company: "United State of Africa",
    Nature: "Remote",
    url: "https://usafrikagov.com/",
    Description: [
      "I collaborate with designers and back-end developers to implement and maintain user interfaces for the company websites and web applications.",
      "I collaborate with other frontend developers to work on the company website and web applications.",
      "I actively participate in agile development processes, including sprint planning, daily stand-ups, and retrospectives, to ensure timely delivery of high-quality software.",
      "I write clean, efficient, and maintainable code using React JS, Next JS framework with tailwind CSS for the styling.",
      "Worked on implementation of website Figma design.",
      "I ensure cross-browser compatibility and responsiveness of web interfaces across various devices and screen sizes",
      "I implement user interface designs with a keen eye for detail, ensuring visual consistency and adherence to brand guidelines.",
      "I conduct several test and debugging of code to ensure the functionality and integrity of web interfaces.",
      "I also collaborate with cross-functional teams to understand project requirements and deliver high-quality solutions within specified timelines.",
    ],
  },
];

export default ExperienceDB;
