const ExperienceDB = [
  {
    id: "1",
    JobRole: "Data Analyst",
    JobType: "",
    StartDay: "August 2023",
    EndDay: "Present",
    Company: "Accessible Publishers Limited",
    Nature: "Onsite",
    url: "https://www.accessiblepublishers.com/",
    Description: [
      "Collect and analyze data from press machines, Cloud Pub, and employee reports to support operational and marketing insights.",
      "Conducted regular data quality assurance, cleansing, and developed structured data models for organizational use.",
      "Identify trends, develop automated data scraping processes, and create report in Power BI and Excel for data driven decision.",
      "Delivered data-driven reports and recommendations for management, and led Excel tutorials to improve team data skills.",
      "Collecting and managing data daily from press machines, Cloud Pub, including exploratory data analysis (EDA).",
      "Identifying trends and patterns in complex datasets.",
      "Quality assurance and data cleansing, using MS Excel and SQL.",
      "Setting up a database for the company datasets for different departments.",
      "Setting up processes and systems to make working with data more efficient",
      "Researching new ways to make use of data.",
      "Analyzed data to award recognition to supervisors, staffs, casuals, apprentice for their performance for every month.",
      "Developing automated processes for data scraping.",
      "Analyzing data to identify trends",
    ],
  },
  {
    id: "2",
    JobRole: "Quantity Surveyor",
    JobType: "",
    StartDay: "April 2022",
    EndDay: "Present",
    Company: "Best Technologies Limited",
    Nature: "OnSite",
    url: "",
    Description: [
      "Measure building and civil engineering works, prepare bills of quantities, and manage material schedules and work programs.",
      "I oversee site engineering and procurement of materials and prepare interim valuations",
      "Price un-priced bills of quantities for tendering and procure materials for the site.",
    ],
  },
  {
    id: "3",
    JobRole: "Data Analysis Tutor",
    JobType: "",
    StartDay: "February 2023",
    EndDay: "Present",
    Company: "Best Technologies Limited",
    Nature: "Part Time",
    url: "",
    Description: [
      "Mentor and guide data analysis newbies",
      "Organize data analysis tutorial classes but online and onsite for data analyst newbies",
      "Organize monthly Microsoft Excel training for Students",
      "Train company staff on how to use excel make their work faster and more efficient.",
    ],
  },
  {
    id: "4",
    JobRole: "Mentor (Tech4Governance)",
    JobType: "https://aspilosfoundation.org.ng/",
    StartDay: "September 2024",
    EndDay: "December 2024",
    Company: "Aspilos Foundation",
    Nature: "Remote",
    url: "",
    Description: [
      "Guided young tech professionals in developing Civic Tech Solutions to address governance challenges.",
      "Provided mentorship on data-driven decision-making and the integration of technology for social impact.",
      "Conducted workshops on data analysis, visualization, and solution prototyping.",
    ],
  },
  {
    id: "5",
    JobRole: "FrontEnd Developer",
    JobType: "Volunteer",
    StartDay: "April 2022",
    EndDay: "December 2023",
    Company: "United State of Africa",
    Nature: "Remote",
    url: "https://usafrikagov.com/",
    Description: [
      "I collaborate with designers and back-end developers to implement and maintain user interfaces for the company websites and web applications.",
      "I collaborate with other frontend developers to work on the company website and web applications.",
      "I actively participate in agile development processes, including sprint planning, daily stand-ups, and retrospectives, to ensure timely delivery of high-quality software.",
      "I write clean, efficient, and maintainable code using React JS, Next JS framework with tailwind CSS for the styling.",
      "Worked on implementation of website Figma design.",
      "I ensure cross-browser compatibility and responsiveness of web interfaces across various devices and screen sizes",
      "I implement user interface designs with a keen eye for detail, ensuring visual consistency and adherence to brand guidelines.",
      "I conduct several test and debugging of code to ensure the functionality and integrity of web interfaces.",
      "I also collaborate with cross-functional teams to understand project requirements and deliver high-quality solutions within specified timelines.",
    ],
  },
];

export default ExperienceDB;
